### ISSUE TITLE
Pop-up doesn't work!

### ISSUE THREAD

**Issue by weberlu88** [h164654156465/ncu-gpa-calculator#3]
擴充功能在學校網域下還是無法運作 QAQ
![圖片](https://user-images.githubusercontent.com/43847259/104091276-6744ff80-52b7-11eb-9e3a-df1821afb907.png)

**Comment by 7xuanlu** [comment]
哈囉 @weberlu88 ，可以幫我確認你已經到**成績查詢**頁面了嗎？
這隻插件目前限制只能在學校網域的那個頁面裡面才能啟動喔。

**Comment by weberlu88** [comment]
你好! 我把chrome關閉重新開啟就能正常使用了，重開後目前沒有遭遇過上述問題!
謝謝~
